#include "main.h"

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
*By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.
*By considering the terms in the Fibonacci sequence whose values do not exceed 4,000,000
*Write a program that finds and prints the sum of the even-valued terms, followed by a new line*/

int main()
{
	int i;
	unsigned long int sum1, sum2, next, sum;

	sum1 = 1;
	sum2 = 2;
	sum = 0;

	for (i = 1; i <= 33; ++i)
	{
		if (sum1 < 4000000 && (sum1 % 2) == 0)
		{
			sum = sum + sum1;
		}
		next = sum1 + sum2;
		sum1 = sum2;
		sum2 = next;
	}

	printf("%lu\n", sum);

	return (0);
}
